version: '3.1'

services:

  web:
    image: nginx
    restart: always
    links: 
      - db
    ports:
      - 8080:80

  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    links:
      - mongo
    command: "node server.js"
    ports:
      - 8081:4000

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - ./db/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  myadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links: 
      - db
    ports:
      - 8082:80

  mongo:
    image: mongo
    restart: always
    volumes: 
      - ./db/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    links:
      - mongo
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example